name: Reindentify file format
description: Reindentify file format
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Report a file to reindentification
  - type: input
    id: puid
    attributes:
      label: puid
      description: Specify the puid of the file
    validations:
      required: true
  - type: input
    id: keep
    attributes:
      label: Keep format?
      description: Conserve this file format in archive
    validations:
      required: true
  - type: textarea
    id: extension
    attributes:
      label: Wrong file extension
      description: The wrong file extension of the files
    validations:
      required: true
  - type: textarea
    id: extension_correct
    attributes:
      label: Correct extension
      description: Specify the expected extension
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Pronom description
      description: The file type description from Pronom.
    validations:
      required: true
  - type: textarea
    id: digiarch_warning
    attributes:
      label: Digiarch warning
      description: The warning specified by digiarch
      render: shell
  - type: textarea
    id: example
    attributes:
      label: Path
      description: Patho file example
    validations:
      required: true