name: Report a file format
description: Report a file format with puid but no action
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Report a file with puid but no action
  - type: input
    id: puid
    attributes:
      label: puid
      description: Specify the puid of the file
    validations:
      required: true
  - type: input
    id: keep
    attributes:
      label: Keep format?
      description: Conserve this file format in archive
    validations:
      required: true
  - type: textarea
    id: Signature
    attributes:
      label: Signature
      description: The signature given by Digiarch
    validations:
      required: true
  - type: textarea
    id: warning
    attributes:
      label: Warning
      description: The warning column given by Digiarch
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Pronom description
      description: The file type description from Pronom.
    validations:
      required: true
  - type: textarea
    id: action
    attributes:
      label: Action
      description: Decided what to do with the file(s)
    validations:
      required: true      
  - type: textarea
    id: example
    attributes:
      label: Path
      description: Patho file example
    validations:
      required: true