name: JSON check

on:
  push:
    paths:
      - '**.json'
      - '**.yml'
      - '**.yaml'

env:
  PYTHON_VERSION: 3.11.6

jobs:
  check-schemata:
    name: Check Schemata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: python -m pip install check-jsonschema
      - name: Check JSON Syntax
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "\\.json$"
      - name: Check YAML Syntax
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ./*.yml
          config_data: |
            extends: default
            rules:
              line-length: disable
      - name: Check JSON Schemata
        run: check-jsonschema --verbose --check-metaschema *.schema.json
      - name: Check Files
        run: |
          for schema in *.schema.json; do
            for ext in "yaml" "yml" "json"; do
              [[ -f "${schema%.schema.json}.$ext" ]] && check-jsonschema --verbose --schemafile "$schema" "${schema%.schema.json}.$ext"
            done
          done