name: Release

on:
  push:
    tags:
      - 'v*.*.*'
env:
  PYTHON_VERSION: 3.11.6

jobs:
  wheel:
    name: Release Files
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Get Tag
        id: tag
        run: echo "tag=$(git tag -l --sort=-version:refname | head -1)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Dependencies
        run: python -m pip install pyyaml
      - name: Generate JSON Files
        run: |
          python3 -c 'import yaml,json,sys;json.dump(yaml.load(open(sys.argv[1]), yaml.Loader), open(sys.argv[2], "w"))' fileformats.yml fileformats.json
          python3 -c 'import yaml,json,sys;json.dump(yaml.load(open(sys.argv[1]), yaml.Loader), open(sys.argv[2], "w"))' custom_signatures.yml custom_signatures.json
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.tag }}
          files: |
            fileformats.yml
            custom_signatures.yml
            fileformats.json
            custom_signatures.json
