name: Stale Branches

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Stale Branches
        uses: crs-k/stale-branches@v6.0.2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          stale-branch-label: 'Stale Branch'
          days-before-stale: 30
          days-before-delete: 730
          compare-branches: 'info'
          comment-updates: true
          tag-committer: true
          max-issues: 50
